---
# Increase Open Limit File
# https://docs.pritunl.com/v1/docs/configuration-5#section-increase-open-file-limit
- block:
  - name: Increase open file limit
    pam_limits:
      domain: "*"
      limit_type: hard
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: "*"
      limit_type: soft
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: root
      limit_type: hard
      limit_item: nofile
      value: 64000

  - name: Increase open file limit
    pam_limits:
      domain: root
      limit_type: soft
      limit_item: nofile
      value: 64000
  when: pritunl_increase_open_limit_file

- name: start mongod
  service:
    name: mongod
    state: started
    enabled: yes
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: start pritunl
  service:
    name: pritunl
    state: started
    enabled: yes

- name: Update pritunl conf file
  template:
    src: "pritunl.conf.j2"
    dest: "/etc/pritunl.conf"
  notify: restart pritunl
  tags:
    - pritunl-update

- name: Check app.server_port option
  shell: pritunl get app.server_port
  register: app_server_port
  failed_when: app_server_port.rc != 0
  changed_when: False
  when: pritunl_server_port is defined
  tags:
    - pritunl-reverse-proxy

- name: "Set app.server_port to {{ pritunl_server_port }}"
  shell: "pritunl set app.server_port {{ pritunl_server_port }}"
  register: resp
  failed_when: resp.rc != 0
  changed_when: "'app.server_port = {{ pritunl_server_port }}' in resp.stdout"
  when: "'app.server_port = {{ pritunl_server_port }}' not in app_server_port.stdout and pritunl_server_port is defined"
  tags:
    - pritunl-reverse-proxy
