---
- name: Add mongodb apt repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/{{ pritunl_mongodb_version }} multiverse
    filename: "mongodb-org-{{ pritunl_mongodb_version }}"
    state: present
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: Add pritunl apt repository
  apt_repository:
    repo: deb http://repo.pritunl.com/stable/apt xenial main
    filename: "pritunl"
    state: present

- name: Add apt keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items: "{{ pritunl_apt_keys }}"

- name: Update package lists
  apt: update_cache=yes

- name: Install mongodb
  apt:
    name: mongodb
    state: latest
    update_cache: no
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: Install pritunl
  apt:
    name: pritunl
    state: latest
    update_cache: no
