---
- name: Add EPEL repository
  dnf:
    name: epel-release
    state: latest
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: Add MongoDB repository
  yum_repository:
    name: mongodb-5.0
    description: MongoDB 5.0 YUM repo
    baseurl: https://repo.mongodb.org/yum/redhat/8/mongodb-org/5.0/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-5.0.asc

- name: Add Pritunl repository
  yum_repository:
    name: pritunl
    description: Pritunl YUM repo
    baseurl: https://repo.pritunl.com/stable/yum/oraclelinux/8/
    gpgkey: https://raw.githubusercontent.com/pritunl/pgp/master/pritunl_repo_pub.asc

- name: Install mongodb
  dnf:
    name: mongodb-org
    state: installed    
  when: not pritunl_mongodb_external and pritunl_mongodb_version is defined

- name: Install pritunl
  dnf:
    name: pritunl
    state: installed

- name: Install pritunl-openvpn
  dnf:
    name: pritunl-openvpn
    state: installed
    allowerasing: yes