---
- include: install.yml

- include: config.yml

- include: reverse-proxy.yml
  when: pritunl_reverse_proxy is defined
  tags: pritunl-reverse-proxy

- include: plugins.yml
  when: pritunl_plugins is defined
  tags: pritunl-plugins
