---
- pip:
    name: "{{ item }}"
    executable: /usr/lib/pritunl/bin/pip
  with_items: "{{ pritunl_plugins_requirements }}"

- name: Creates pritunl plugins directory
  file:
    path: /var/lib/pritunl/plugins
    state: directory
    mode: 0775

- name: install plugins
  template:
    src: "pritunl-plugin-{{ item }}.j2"
    dest: "/var/lib/pritunl/plugins/{{ item }}.py"
  notify: restart pritunl
  when: pritunl_plugins | selectattr("name","equalto",item) | list | count == 1
  with_items:
    - default-groups
