---
- name: Install plugins dependencies
  pip:
    name: "{{ item }}"
    executable: /usr/lib/pritunl/bin/pip
  with_items: "{{ pritunl_plugins_pip_requirements }}"

- block:
  - name: Install python-ldap dependencies
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: no
    with_items:
      - libsasl2-dev
      - python-dev
      - libldap2-dev
      - libssl-dev

  - name: Install python-ldap dependencies
    pip:
      name: python-ldap
      executable: /usr/lib/pritunl/bin/pip

  when: pritunl_plugins | selectattr("name","equalto","ldap") | list | count == 1

- name: Creates pritunl plugins directory
  file:
    path: /var/lib/pritunl/plugins
    state: directory
    mode: 0775

- name: install plugins
  template:
    src: "pritunl-plugin-{{ item }}.j2"
    dest: "/var/lib/pritunl/plugins/{{ item }}.py"
  notify: restart pritunl
  when: pritunl_plugins | selectattr("name","equalto",item) | list | count == 1
  with_items:
    - graylog
    - default-groups

- name: install ldap plugin
  template:
    src: pritunl-plugin-ldap.j2
    dest: /var/lib/pritunl/plugins/ldap.py
  notify: restart pritunl
  when: pritunl_plugins | selectattr("name","equalto","ldap") | list | count == 1 and pritunl_api is defined
